package cmd

import (
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/1004ms/Meriotify/src/utils"
)

// EnsureMeriotifyFeatures keeps the native Hub and lightweight core extension
// enabled for both fresh installs and self-updates.
func EnsureMeriotifyFeatures() {
	changed := false
	changed = ensureFeatureListValue("custom_apps", "meriotify") || changed
	changed = ensureFeatureListValue("extensions", "meriotify-core.js") || changed
	changed = ensureFeatureListValue("extensions", "shuffle+.js") || changed
	if changed {
		_ = cfg.Write()
	}
	writeMeriotifyLocale()
}

func writeMeriotifyLocale() {
	language := strings.ToLower(strings.TrimSpace(os.Getenv("MERIOTIFY_LANG")))
	if language != "it" && language != "en" {
		data, err := os.ReadFile(filepath.Join(utils.GetMeriotifyFolder(), "language"))
		if err == nil {
			language = strings.ToLower(strings.TrimSpace(string(data)))
		}
	}
	if language != "it" {
		language = "en"
	}

	appPath, err := utils.GetCustomAppPath("meriotify")
	if err != nil {
		return
	}
	content := "// Generated by Meriotify setup from the installer language.\nwindow.MeriotifyLocale = \"" + language + "\";\n"
	_ = os.WriteFile(filepath.Join(appPath, "locale.js"), []byte(content), 0600)
}

func ensureFeatureListValue(field, value string) bool {
	key, err := featureSection.GetKey(field)
	if err != nil {
		return false
	}

	values := key.Strings("|")
	for _, current := range values {
		if strings.EqualFold(strings.TrimSpace(current), value) {
			return false
		}
	}

	values = append(values, value)
	sort.Strings(values)
	key.SetValue(strings.Join(values, "|"))
	return true
}
